[package]
name = "my-template"
version = "0.1.0"
description = "a simple widget based template"
authors = ["qzen"]
license = "MIT"
edition = "2024"

[dependencies]
sysinfo = "0.30"
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
glob = "0.3.3"
